BOOKS_PATH = "./data/raw/books.csv"
BOOK_TAGS_PATH = "./data/raw/book_tags.csv"
TAGS_PATH = "./data/raw/tags.csv"
USER_DATA_PATH = "./data/raw/goodreads_library_export.csv"
DATASET_PATH = "./data/processed/dataset.csv"
